name: Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: requirements-dev.txt

      - name: Set up the virtualenv
        run: make venv

      - name: Run yamllint
        run: make lint
