name: Validate

on:
  push:
    branches: [main]
  pull_request:

jobs:
  blueprints:
    name: Blueprints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: requirements-dev.txt

      - name: Set up the virtualenv
        run: make venv

      - name: Validate blueprints
        run: make validate

      - name: Check README is up to date
        run: make readme-check
